export const products = [
  {
    id: 1,
    name: 'Mama Gold Rice',
    image: require('../static/assets/rice.jpg'),
    category: 'Product Merchant',
    price: 23000,
  },
  {
    id: 2,
    name: 'Wrist Watch',
    image: require('../static/assets/wristwatch.jpg'),
    category: 'Service Merchant',
    price: 10000,
  },
  {
    id: 3,
    name: 'Wachine Machine',
    image: require('../static/assets/washing machine.jpg'),
    category: 'Product Merchant',
    price: 60000,
  },
  {
    id: 4,
    name: 'Gas Cooker',
    image: require('../static/assets/gas cooker.jpg'),
    category: 'Service Merchant',
    price: 30000,
  },
  {
    id: 5,
    name: 'Vinegar Sellamin',
    image: require('../static/assets/vinegar.jpg'),
    category: 'Product Merchant',
  },
  {
    id: 6,
    name: 'Thermacool Refrigerator',
    image: require('../static/assets/refrigerator.jpg'),
    category: 'Product Merchant',
    price: 150000,
  },
  {
    id: 7,
    name: 'Maggi Chicken',
    image: require('../static/assets/maggi.jpg'),
    category: 'Service Merchant',
    price: 2000,
  },
  {
    id: 8,
    name: 'Milo Beverage',
    image: require('../static/assets/milo.jpg'),
    price: 1500,
    category: 'Service Merchant',
  },
  {
    id: 9,
    name: 'Phillips Pressing Iron',
    image: require('../static/assets/iron.jpg'),
    category: 'Product Merchant',
  },
  {
    id: 10,
    name: 'Electric Kettle',
    image: require('../static/assets/kettle.jpg'),
    category: 'Product Merchant',
    price: 7000,
  },
  {
    id: 11,
    name: 'HP Printer',
    image: require('../static/assets/printer.png'),
    price: 40000,
    category: 'Service Merchant',
  },
  {
    id: 12,
    name: 'Fitted Shirt',
    image: require('../static/assets/shirt.png'),
    category: 'Product Merchant',
    price: 6000,
  },
  {
    id: 13,
    name: 'Toasting Machine',
    image: require('../static/assets/toaster.jpg'),
    category: 'Service Merchant',
    price: 23000,
  },
  {
    id: 14,
    name: 'Brazillian Wig',
    image: require('../static/assets/wig.jpg'),
    category: 'Service Merchant',
    price: 90000,
  },
  {
    id: 15,
    name: 'PS4 Game',
    image: require('../static/assets/ps4.jpg'),
    category: 'Product Merchant',
    price: 560000,
  },
  {
    id: 16,
    name: 'Barbie Doll',
    image: require('../static/assets/doll.jpg'),
    price: 4000,
    category: 'Service Merchant',
  },
  {
    id: 17,
    name: 'Fotomi',
    image: require('../static/assets/fotomi.jpg'),
    category: 'Product Merchant',
    price: 40000,
  },
  {
    id: 18,
    name: 'Golden Morn',
    image: require('../static/assets/golden morn.jpg'),
    category: 'Service Merchant',
    price: 2000,
  },
  {
    id: 19,
    name: 'iPhone',
    image: require('../static/assets/iphone.png'),
    category: 'Service Merchant',
    price: 360000,
  },
  {
    id: 20,
    name: 'Bluetooth Speaker',
    image: require('../static/assets/Bluetooth Speaker.jpg'),
    category: 'Service Merchant',
    price: 14000,
  },
]
